name: dart_polymer_supervising_presenter
description: A sample Polymer application, showing the Supervising Presenter pattern
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  core_elements: any
  polymer: any
transformers:
- polymer:
    entry_points: web/index.html
